# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Add-EnvPath.ps1
. $PSScriptRoot\Beep.ps1
. $PSScriptRoot\Copy-GitRepo.ps1
. $PSScriptRoot\Download-GitUser.ps1
. $PSScriptRoot\Find-CmdParam.ps1
. $PSScriptRoot\Get-ACLInfo.ps1
. $PSScriptRoot\Get-ComObject.ps1
. $PSScriptRoot\Get-DotNetFrameworkVersion.ps1
. $PSScriptRoot\Get-EnvPath.ps1
. $PSScriptRoot\Get-Functions.ps1
. $PSScriptRoot\Get-PartitionInfo.ps1
. $PSScriptRoot\Get-PipelineInfo.ps1
. $PSScriptRoot\Invoke-WebDownload
. $PSScriptRoot\List-SpecialFolders.ps1
. $PSScriptRoot\Max-PartitionSize.ps1
. $PSScriptRoot\New-DynamicParam.ps1
. $PSScriptRoot\New-Shortcut.ps1
. $PSScriptRoot\Open-NPP.ps1
. $PSScriptRoot\Open-Script.ps1
. $PSScriptRoot\Out-ISETab.ps1
. $PSScriptRoot\Remove-EnvPath.ps1
. $PSScriptRoot\Restart-Process.ps1
. $PSScriptRoot\Search-WinCatalog.ps1
. $PSScriptRoot\Select-All.ps1
. $PSScriptRoot\Set-AutoLogin.ps1
. $PSScriptRoot\Show-Cmdlet.ps1
. $PSScriptRoot\Shutdown-ESXI.ps1
. $PSScriptRoot\Source-Directory.ps1
. $PSScriptRoot\Start-ConsoleCommand.ps1
. $PSScriptRoot\Sync-GitUser
. $PSScriptRoot\Test-IfAdmin.ps1
